#登陆相关配置
login:
  #开放的模拟登陆api服务器地址
  api: "http://www.zimo.wiki:8080/wisedu-unified-login-api-v1.0/api/login"
#用户组配置
users:
  #单个用户配置
  - user:
      #username 学号或者工号
      username: '1920070303114'
      #password 密码
      password: 'IceTiki'
      #address 地址，定位信息
      address: 中国广东省惠州市第一厕所第三坑位
      #email 接受通知消息的邮箱
      email: 461009747@qq.com
      #school 学校全称
      school: 惠州学院
  #多用户配置，将下面的注释去掉即可，如果有表单内容有图片，不建议使用多用户配置
  #昨晚尝试用多用户配置，显示一个设备只能完成一个签到任务
#  - user:
#      #username 学号或者工号
#      username: 161105024
#      #password 密码
#      password: 161105024
#      #address 地址
#      address: 中国四川省成都市金牛区一环路北1段-129号-附9号
#      #email 接受通知消息的邮箱
#      email: 461009747@qq.com
#      school: 宜宾学院
#今日校园相关配置
cpdaily:
  #单选的默认选项配置
  answer: 正常，没有症状 

Info:
  ServerChan: # 填写Server酱的SCKEY
  Qsmg: # 填写Qsmg酱的SCKEY
  Email:
    enable: true
    server: smtp.exmail.qq.com # 填写邮件的smtp服务器
    port: 465 # 填写邮件服务器的端口号
    account: '' # 邮件服务器登录用户名
    password: '' # 邮件服务器登录密码
